### PR TITLE
Fixed Github authorization with rte-bot

### PR DESCRIPTION
**Pull request by JGrothoff**

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
You can retrigger a build in the travis interface if you have enough rights

**Comment by JGrothoff** [comment]
Thanks ;-). But I already tried it. Rebuilding in travis doesn't consider the new .yml file.

And i don't know why my commit to the master branch isn't visible on travis. Even this pull request isn't there. Although i made "Small changes to trigger travis." on ovm or source files.

**Comment by Stasik0** [comment]
Its because you never merged. Pr builds have no access to secret variables. Otherwise people would just steal them or deface webpage with a pull request.

**Comment by JGrothoff** [comment]
Nope. Merging this PR didn't help either. PR 39 is listed in travis, although it is not merged. Travis seems to ignore me :-D.
And as explained before, a direct commit to master branch didn't trigger travis. I also see no "ignore" definition in .yml file, which would have travis stopped from triggering.

**Comment by JGrothoff** [comment]
Aha, its realy travis ignoring me 👎 .
travis abuse

**Comment by Stasik0** [comment]
Travis will build the pr, but it will not allow bot to authorize and update the webpage.

**Pull request merged**
