### PR TITLE
activating clang on travis

### PR DESCRIPTION
**Pull request by HolgerJeromin**
try clang with the new travis stuff

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
The build failure is a problem with the normal scripts. They are a bit chaotic when adding another compiler. :-)

Probably the documentation should be generated only once (gcc and 32 bit compile?)

**Comment by Stasik0** [comment]
I see two 17 minute timeouts?

**Comment by HolgerJeromin** [comment]
Yes. They are from a rm of the generated doc.

**Comment by LEvertz** [comment]
works now --> will close this

**Pull request closed without merging**
